version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8100:3100
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: focus
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .mysqlDatabase:/var/lib/mysql
    ports:
      - 33066:3306
